//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfapp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public int ManufactureID { get; set; }
        public string ManufactureName { get; set; }
    }
}
