//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfapp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PtoductArtideNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductUnit { get; set; }
        public Nullable<int> ProductCost { get; set; }
        public Nullable<int> ProductMaxSate { get; set; }
        public string ProductManufacturer { get; set; }
        public string ProductProvider { get; set; }
        public string ProductCategory { get; set; }
        public Nullable<int> ProductSale { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<double> ProductPhoto { get; set; }
    }
}
