//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfapp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public int ProviderID { get; set; }
        public string ProviderName { get; set; }
    }
}
